# Generated by Django 3.2.25 on 2024-10-02 02:19

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_auto_20241002_0033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
